// Code generated by wit-bindgen-go. DO NOT EDIT.

package types

import (
	"go.bytecodealliance.org/cm"
	"unsafe"
)

// ErrorResponseShape is used for storage in variant or result types.
type ErrorResponseShape struct {
	_     cm.HostLayout
	shape [unsafe.Sizeof(ErrorResponse{})]byte
}
