// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package types represents the imported interface "github:server/types@0.1.0".
//
// Core types for request/response
package types

import (
	"go.bytecodealliance.org/cm"
)

// ErrorCode represents the string "github:server/types@0.1.0#error-code".
//
// Common types
//
//	type error-code = string
type ErrorCode string

// ErrorResponse represents the record "github:server/types@0.1.0#error-response".
//
//	record error-response {
//		code: error-code,
//		message: string,
//	}
type ErrorResponse struct {
	_       cm.HostLayout `json:"-"`
	Code    ErrorCode     `json:"code"`
	Message string        `json:"message"`
}

// ToolResult represents the variant "github:server/types@0.1.0#tool-result".
//
//	variant tool-result {
//		success(string),
//		error(error-response),
//	}
type ToolResult cm.Variant[uint8, ErrorResponseShape, ErrorResponse]

// ToolResultSuccess returns a [ToolResult] of case "success".
func ToolResultSuccess(data string) ToolResult {
	return cm.New[ToolResult](0, data)
}

// Success returns a non-nil *[string] if [ToolResult] represents the variant case "success".
func (self *ToolResult) Success() *string {
	return cm.Case[string](self, 0)
}

// ToolResultError returns a [ToolResult] of case "error".
func ToolResultError(data ErrorResponse) ToolResult {
	return cm.New[ToolResult](1, data)
}

// Error returns a non-nil *[ErrorResponse] if [ToolResult] represents the variant case "error".
func (self *ToolResult) Error() *ErrorResponse {
	return cm.Case[ErrorResponse](self, 1)
}

var _ToolResultStrings = [2]string{
	"success",
	"error",
}

// String implements [fmt.Stringer], returning the variant case name of v.
func (v ToolResult) String() string {
	return _ToolResultStrings[v.Tag()]
}

// Pagination represents the record "github:server/types@0.1.0#pagination".
//
// Pagination
//
//	record pagination {
//		page: u32,
//		per-page: u32,
//	}
type Pagination struct {
	_       cm.HostLayout `json:"-"`
	Page    uint32        `json:"page"`
	PerPage uint32        `json:"per-page"`
}

// ToolRequest represents the record "github:server/types@0.1.0#tool-request".
//
// Tool call request structure
//
//	record tool-request {
//		name: string,
//		params: string,
//	}
type ToolRequest struct {
	_      cm.HostLayout `json:"-"`
	Name   string        `json:"name"`
	Params string        `json:"params"`
}

// ResourceRequest represents the record "github:server/types@0.1.0#resource-request".
//
// Resource request structure
//
//	record resource-request {
//		uri: string,
//	}
type ResourceRequest struct {
	_   cm.HostLayout `json:"-"`
	URI string        `json:"uri"`
}

// PromptRequest represents the record "github:server/types@0.1.0#prompt-request".
//
// Prompt request structure
//
//	record prompt-request {
//		name: string,
//		params: string,
//	}
type PromptRequest struct {
	_      cm.HostLayout `json:"-"`
	Name   string        `json:"name"`
	Params string        `json:"params"`
}
