// Code generated by wit-bindgen-go. DO NOT EDIT.

package repositories

// This file contains wasmimport and wasmexport declarations for "github:server@0.1.0".

//go:wasmexport github:server/repositories@0.1.0#search-repositories
//export github:server/repositories@0.1.0#search-repositories
func wasmexport_SearchRepositories(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.SearchRepositories(request)
	result = &result_
	return
}

//go:wasmexport github:server/repositories@0.1.0#get-file-contents
//export github:server/repositories@0.1.0#get-file-contents
func wasmexport_GetFileContents(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.GetFileContents(request)
	result = &result_
	return
}

//go:wasmexport github:server/repositories@0.1.0#create-or-update-file
//export github:server/repositories@0.1.0#create-or-update-file
func wasmexport_CreateOrUpdateFile(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.CreateOrUpdateFile(request)
	result = &result_
	return
}

//go:wasmexport github:server/repositories@0.1.0#delete-file
//export github:server/repositories@0.1.0#delete-file
func wasmexport_DeleteFile(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.DeleteFile(request)
	result = &result_
	return
}

//go:wasmexport github:server/repositories@0.1.0#list-commits
//export github:server/repositories@0.1.0#list-commits
func wasmexport_ListCommits(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.ListCommits(request)
	result = &result_
	return
}

//go:wasmexport github:server/repositories@0.1.0#get-commit
//export github:server/repositories@0.1.0#get-commit
func wasmexport_GetCommit(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.GetCommit(request)
	result = &result_
	return
}

//go:wasmexport github:server/repositories@0.1.0#search-code
//export github:server/repositories@0.1.0#search-code
func wasmexport_SearchCode(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.SearchCode(request)
	result = &result_
	return
}

//go:wasmexport github:server/repositories@0.1.0#list-branches
//export github:server/repositories@0.1.0#list-branches
func wasmexport_ListBranches(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.ListBranches(request)
	result = &result_
	return
}

//go:wasmexport github:server/repositories@0.1.0#create-branch
//export github:server/repositories@0.1.0#create-branch
func wasmexport_CreateBranch(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.CreateBranch(request)
	result = &result_
	return
}

//go:wasmexport github:server/repositories@0.1.0#list-tags
//export github:server/repositories@0.1.0#list-tags
func wasmexport_ListTags(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.ListTags(request)
	result = &result_
	return
}

//go:wasmexport github:server/repositories@0.1.0#get-tag
//export github:server/repositories@0.1.0#get-tag
func wasmexport_GetTag(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.GetTag(request)
	result = &result_
	return
}

//go:wasmexport github:server/repositories@0.1.0#list-releases
//export github:server/repositories@0.1.0#list-releases
func wasmexport_ListReleases(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.ListReleases(request)
	result = &result_
	return
}

//go:wasmexport github:server/repositories@0.1.0#get-latest-release
//export github:server/repositories@0.1.0#get-latest-release
func wasmexport_GetLatestRelease(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.GetLatestRelease(request)
	result = &result_
	return
}

//go:wasmexport github:server/repositories@0.1.0#get-release-by-tag
//export github:server/repositories@0.1.0#get-release-by-tag
func wasmexport_GetReleaseByTag(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.GetReleaseByTag(request)
	result = &result_
	return
}

//go:wasmexport github:server/repositories@0.1.0#push-files
//export github:server/repositories@0.1.0#push-files
func wasmexport_PushFiles(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.PushFiles(request)
	result = &result_
	return
}

//go:wasmexport github:server/repositories@0.1.0#create-repository
//export github:server/repositories@0.1.0#create-repository
func wasmexport_CreateRepository(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.CreateRepository(request)
	result = &result_
	return
}

//go:wasmexport github:server/repositories@0.1.0#fork-repository
//export github:server/repositories@0.1.0#fork-repository
func wasmexport_ForkRepository(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.ForkRepository(request)
	result = &result_
	return
}

//go:wasmexport github:server/repositories@0.1.0#star-repository
//export github:server/repositories@0.1.0#star-repository
func wasmexport_StarRepository(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.StarRepository(request)
	result = &result_
	return
}

//go:wasmexport github:server/repositories@0.1.0#unstar-repository
//export github:server/repositories@0.1.0#unstar-repository
func wasmexport_UnstarRepository(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.UnstarRepository(request)
	result = &result_
	return
}

//go:wasmexport github:server/repositories@0.1.0#list-starred-repositories
//export github:server/repositories@0.1.0#list-starred-repositories
func wasmexport_ListStarredRepositories(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.ListStarredRepositories(request)
	result = &result_
	return
}
