// Code generated by wit-bindgen-go. DO NOT EDIT.

package repositories

// Exports represents the caller-defined exports from "github:server/repositories@0.1.0".
var Exports struct {
	// SearchRepositories represents the caller-defined, exported function "search-repositories".
	//
	// Search for repositories
	//
	//	search-repositories: func(request: tool-request) -> tool-result
	SearchRepositories func(request ToolRequest) (result ToolResult)

	// GetFileContents represents the caller-defined, exported function "get-file-contents".
	//
	// Get file contents
	//
	//	get-file-contents: func(request: tool-request) -> tool-result
	GetFileContents func(request ToolRequest) (result ToolResult)

	// CreateOrUpdateFile represents the caller-defined, exported function "create-or-update-file".
	//
	// Create or update files
	//
	//	create-or-update-file: func(request: tool-request) -> tool-result
	CreateOrUpdateFile func(request ToolRequest) (result ToolResult)

	// DeleteFile represents the caller-defined, exported function "delete-file".
	//
	// Delete files
	//
	//	delete-file: func(request: tool-request) -> tool-result
	DeleteFile func(request ToolRequest) (result ToolResult)

	// ListCommits represents the caller-defined, exported function "list-commits".
	//
	// List commits
	//
	//	list-commits: func(request: tool-request) -> tool-result
	ListCommits func(request ToolRequest) (result ToolResult)

	// GetCommit represents the caller-defined, exported function "get-commit".
	//
	// Get specific commit
	//
	//	get-commit: func(request: tool-request) -> tool-result
	GetCommit func(request ToolRequest) (result ToolResult)

	// SearchCode represents the caller-defined, exported function "search-code".
	//
	// Search code
	//
	//	search-code: func(request: tool-request) -> tool-result
	SearchCode func(request ToolRequest) (result ToolResult)

	// ListBranches represents the caller-defined, exported function "list-branches".
	//
	// List branches
	//
	//	list-branches: func(request: tool-request) -> tool-result
	ListBranches func(request ToolRequest) (result ToolResult)

	// CreateBranch represents the caller-defined, exported function "create-branch".
	//
	// Create branch
	//
	//	create-branch: func(request: tool-request) -> tool-result
	CreateBranch func(request ToolRequest) (result ToolResult)

	// ListTags represents the caller-defined, exported function "list-tags".
	//
	// List tags
	//
	//	list-tags: func(request: tool-request) -> tool-result
	ListTags func(request ToolRequest) (result ToolResult)

	// GetTag represents the caller-defined, exported function "get-tag".
	//
	// Get tag
	//
	//	get-tag: func(request: tool-request) -> tool-result
	GetTag func(request ToolRequest) (result ToolResult)

	// ListReleases represents the caller-defined, exported function "list-releases".
	//
	// List releases
	//
	//	list-releases: func(request: tool-request) -> tool-result
	ListReleases func(request ToolRequest) (result ToolResult)

	// GetLatestRelease represents the caller-defined, exported function "get-latest-release".
	//
	// Get latest release
	//
	//	get-latest-release: func(request: tool-request) -> tool-result
	GetLatestRelease func(request ToolRequest) (result ToolResult)

	// GetReleaseByTag represents the caller-defined, exported function "get-release-by-tag".
	//
	// Get release by tag
	//
	//	get-release-by-tag: func(request: tool-request) -> tool-result
	GetReleaseByTag func(request ToolRequest) (result ToolResult)

	// PushFiles represents the caller-defined, exported function "push-files".
	//
	// Push files
	//
	//	push-files: func(request: tool-request) -> tool-result
	PushFiles func(request ToolRequest) (result ToolResult)

	// CreateRepository represents the caller-defined, exported function "create-repository".
	//
	// Create repository
	//
	//	create-repository: func(request: tool-request) -> tool-result
	CreateRepository func(request ToolRequest) (result ToolResult)

	// ForkRepository represents the caller-defined, exported function "fork-repository".
	//
	// Fork repository
	//
	//	fork-repository: func(request: tool-request) -> tool-result
	ForkRepository func(request ToolRequest) (result ToolResult)

	// StarRepository represents the caller-defined, exported function "star-repository".
	//
	// Star/unstar repository
	//
	//	star-repository: func(request: tool-request) -> tool-result
	StarRepository func(request ToolRequest) (result ToolResult)

	// UnstarRepository represents the caller-defined, exported function "unstar-repository".
	//
	//	unstar-repository: func(request: tool-request) -> tool-result
	UnstarRepository func(request ToolRequest) (result ToolResult)

	// ListStarredRepositories represents the caller-defined, exported function "list-starred-repositories".
	//
	// List starred repositories
	//
	//	list-starred-repositories: func(request: tool-request) -> tool-result
	ListStarredRepositories func(request ToolRequest) (result ToolResult)
}
