// Code generated by wit-bindgen-go. DO NOT EDIT.

package security

// This file contains wasmimport and wasmexport declarations for "github:server@0.1.0".

//go:wasmexport github:server/security@0.1.0#get-code-scanning-alert
//export github:server/security@0.1.0#get-code-scanning-alert
func wasmexport_GetCodeScanningAlert(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.GetCodeScanningAlert(request)
	result = &result_
	return
}

//go:wasmexport github:server/security@0.1.0#list-code-scanning-alerts
//export github:server/security@0.1.0#list-code-scanning-alerts
func wasmexport_ListCodeScanningAlerts(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.ListCodeScanningAlerts(request)
	result = &result_
	return
}

//go:wasmexport github:server/security@0.1.0#get-secret-scanning-alert
//export github:server/security@0.1.0#get-secret-scanning-alert
func wasmexport_GetSecretScanningAlert(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.GetSecretScanningAlert(request)
	result = &result_
	return
}

//go:wasmexport github:server/security@0.1.0#list-secret-scanning-alerts
//export github:server/security@0.1.0#list-secret-scanning-alerts
func wasmexport_ListSecretScanningAlerts(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.ListSecretScanningAlerts(request)
	result = &result_
	return
}

//go:wasmexport github:server/security@0.1.0#get-dependabot-alert
//export github:server/security@0.1.0#get-dependabot-alert
func wasmexport_GetDependabotAlert(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.GetDependabotAlert(request)
	result = &result_
	return
}

//go:wasmexport github:server/security@0.1.0#list-dependabot-alerts
//export github:server/security@0.1.0#list-dependabot-alerts
func wasmexport_ListDependabotAlerts(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.ListDependabotAlerts(request)
	result = &result_
	return
}

//go:wasmexport github:server/security@0.1.0#list-global-security-advisories
//export github:server/security@0.1.0#list-global-security-advisories
func wasmexport_ListGlobalSecurityAdvisories(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.ListGlobalSecurityAdvisories(request)
	result = &result_
	return
}

//go:wasmexport github:server/security@0.1.0#get-global-security-advisory
//export github:server/security@0.1.0#get-global-security-advisory
func wasmexport_GetGlobalSecurityAdvisory(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.GetGlobalSecurityAdvisory(request)
	result = &result_
	return
}

//go:wasmexport github:server/security@0.1.0#list-repository-security-advisories
//export github:server/security@0.1.0#list-repository-security-advisories
func wasmexport_ListRepositorySecurityAdvisories(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.ListRepositorySecurityAdvisories(request)
	result = &result_
	return
}

//go:wasmexport github:server/security@0.1.0#list-org-repository-security-advisories
//export github:server/security@0.1.0#list-org-repository-security-advisories
func wasmexport_ListOrgRepositorySecurityAdvisories(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.ListOrgRepositorySecurityAdvisories(request)
	result = &result_
	return
}
