// Code generated by wit-bindgen-go. DO NOT EDIT.

package security

// Exports represents the caller-defined exports from "github:server/security@0.1.0".
var Exports struct {
	// GetCodeScanningAlert represents the caller-defined, exported function "get-code-scanning-alert".
	//
	// Code scanning
	//
	//	get-code-scanning-alert: func(request: tool-request) -> tool-result
	GetCodeScanningAlert func(request ToolRequest) (result ToolResult)

	// ListCodeScanningAlerts represents the caller-defined, exported function "list-code-scanning-alerts".
	//
	//	list-code-scanning-alerts: func(request: tool-request) -> tool-result
	ListCodeScanningAlerts func(request ToolRequest) (result ToolResult)

	// GetSecretScanningAlert represents the caller-defined, exported function "get-secret-scanning-alert".
	//
	// Secret scanning
	//
	//	get-secret-scanning-alert: func(request: tool-request) -> tool-result
	GetSecretScanningAlert func(request ToolRequest) (result ToolResult)

	// ListSecretScanningAlerts represents the caller-defined, exported function "list-secret-scanning-alerts".
	//
	//	list-secret-scanning-alerts: func(request: tool-request) -> tool-result
	ListSecretScanningAlerts func(request ToolRequest) (result ToolResult)

	// GetDependabotAlert represents the caller-defined, exported function "get-dependabot-alert".
	//
	// Dependabot
	//
	//	get-dependabot-alert: func(request: tool-request) -> tool-result
	GetDependabotAlert func(request ToolRequest) (result ToolResult)

	// ListDependabotAlerts represents the caller-defined, exported function "list-dependabot-alerts".
	//
	//	list-dependabot-alerts: func(request: tool-request) -> tool-result
	ListDependabotAlerts func(request ToolRequest) (result ToolResult)

	// ListGlobalSecurityAdvisories represents the caller-defined, exported function "list-global-security-advisories".
	//
	// Security advisories
	//
	//	list-global-security-advisories: func(request: tool-request) -> tool-result
	ListGlobalSecurityAdvisories func(request ToolRequest) (result ToolResult)

	// GetGlobalSecurityAdvisory represents the caller-defined, exported function "get-global-security-advisory".
	//
	//	get-global-security-advisory: func(request: tool-request) -> tool-result
	GetGlobalSecurityAdvisory func(request ToolRequest) (result ToolResult)

	// ListRepositorySecurityAdvisories represents the caller-defined, exported function "list-repository-security-advisories".
	//
	//	list-repository-security-advisories: func(request: tool-request) -> tool-result
	ListRepositorySecurityAdvisories func(request ToolRequest) (result ToolResult)

	// ListOrgRepositorySecurityAdvisories represents the caller-defined, exported function "list-org-repository-security-advisories".
	//
	//	list-org-repository-security-advisories: func(request: tool-request) -> tool-result
	ListOrgRepositorySecurityAdvisories func(request ToolRequest) (result ToolResult)
}
