// Code generated by wit-bindgen-go. DO NOT EDIT.

package projects

// Exports represents the caller-defined exports from "github:server/projects@0.1.0".
var Exports struct {
	// ListProjects represents the caller-defined, exported function "list-projects".
	//
	//	list-projects: func(request: tool-request) -> tool-result
	ListProjects func(request ToolRequest) (result ToolResult)

	// GetProject represents the caller-defined, exported function "get-project".
	//
	//	get-project: func(request: tool-request) -> tool-result
	GetProject func(request ToolRequest) (result ToolResult)

	// ListProjectFields represents the caller-defined, exported function "list-project-fields".
	//
	//	list-project-fields: func(request: tool-request) -> tool-result
	ListProjectFields func(request ToolRequest) (result ToolResult)

	// GetProjectField represents the caller-defined, exported function "get-project-field".
	//
	//	get-project-field: func(request: tool-request) -> tool-result
	GetProjectField func(request ToolRequest) (result ToolResult)

	// ListProjectItems represents the caller-defined, exported function "list-project-items".
	//
	//	list-project-items: func(request: tool-request) -> tool-result
	ListProjectItems func(request ToolRequest) (result ToolResult)

	// GetProjectItem represents the caller-defined, exported function "get-project-item".
	//
	//	get-project-item: func(request: tool-request) -> tool-result
	GetProjectItem func(request ToolRequest) (result ToolResult)

	// AddProjectItem represents the caller-defined, exported function "add-project-item".
	//
	//	add-project-item: func(request: tool-request) -> tool-result
	AddProjectItem func(request ToolRequest) (result ToolResult)

	// DeleteProjectItem represents the caller-defined, exported function "delete-project-item".
	//
	//	delete-project-item: func(request: tool-request) -> tool-result
	DeleteProjectItem func(request ToolRequest) (result ToolResult)
}
