// Code generated by wit-bindgen-go. DO NOT EDIT.

package projects

// This file contains wasmimport and wasmexport declarations for "github:server@0.1.0".

//go:wasmexport github:server/projects@0.1.0#list-projects
//export github:server/projects@0.1.0#list-projects
func wasmexport_ListProjects(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.ListProjects(request)
	result = &result_
	return
}

//go:wasmexport github:server/projects@0.1.0#get-project
//export github:server/projects@0.1.0#get-project
func wasmexport_GetProject(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.GetProject(request)
	result = &result_
	return
}

//go:wasmexport github:server/projects@0.1.0#list-project-fields
//export github:server/projects@0.1.0#list-project-fields
func wasmexport_ListProjectFields(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.ListProjectFields(request)
	result = &result_
	return
}

//go:wasmexport github:server/projects@0.1.0#get-project-field
//export github:server/projects@0.1.0#get-project-field
func wasmexport_GetProjectField(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.GetProjectField(request)
	result = &result_
	return
}

//go:wasmexport github:server/projects@0.1.0#list-project-items
//export github:server/projects@0.1.0#list-project-items
func wasmexport_ListProjectItems(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.ListProjectItems(request)
	result = &result_
	return
}

//go:wasmexport github:server/projects@0.1.0#get-project-item
//export github:server/projects@0.1.0#get-project-item
func wasmexport_GetProjectItem(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.GetProjectItem(request)
	result = &result_
	return
}

//go:wasmexport github:server/projects@0.1.0#add-project-item
//export github:server/projects@0.1.0#add-project-item
func wasmexport_AddProjectItem(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.AddProjectItem(request)
	result = &result_
	return
}

//go:wasmexport github:server/projects@0.1.0#delete-project-item
//export github:server/projects@0.1.0#delete-project-item
func wasmexport_DeleteProjectItem(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.DeleteProjectItem(request)
	result = &result_
	return
}
