// Code generated by wit-bindgen-go. DO NOT EDIT.

package types

import (
	"go.bytecodealliance.org/cm"
	"unsafe"
)

// TupleListU8BoolShape is used for storage in variant or result types.
type TupleListU8BoolShape struct {
	_     cm.HostLayout
	shape [unsafe.Sizeof(cm.Tuple[cm.List[uint8], bool]{})]byte
}

// DescriptorStatShape is used for storage in variant or result types.
type DescriptorStatShape struct {
	_     cm.HostLayout
	shape [unsafe.Sizeof(DescriptorStat{})]byte
}

// OptionDirectoryEntryShape is used for storage in variant or result types.
type OptionDirectoryEntryShape struct {
	_     cm.HostLayout
	shape [unsafe.Sizeof(cm.Option[DirectoryEntry]{})]byte
}
