// Code generated by wit-bindgen-go. DO NOT EDIT.

package resources

import (
	"github.com/github/github-mcp-server/internal/github/server/types"
	"go.bytecodealliance.org/cm"
)

func lift_ResourceRequest(f0 *uint8, f1 uint32) (v types.ResourceRequest) {
	v.URI = cm.LiftString[string](f0, f1)
	return
}
