// Code generated by wit-bindgen-go. DO NOT EDIT.

package resources

// This file contains wasmimport and wasmexport declarations for "github:server@0.1.0".

//go:wasmexport github:server/resources@0.1.0#get-repository-resource
//export github:server/resources@0.1.0#get-repository-resource
func wasmexport_GetRepositoryResource(request0 *uint8, request1 uint32) (result *ToolResult) {
	request := lift_ResourceRequest((*uint8)(request0), (uint32)(request1))
	result_ := Exports.GetRepositoryResource(request)
	result = &result_
	return
}

//go:wasmexport github:server/resources@0.1.0#get-repository-branch-resource
//export github:server/resources@0.1.0#get-repository-branch-resource
func wasmexport_GetRepositoryBranchResource(request0 *uint8, request1 uint32) (result *ToolResult) {
	request := lift_ResourceRequest((*uint8)(request0), (uint32)(request1))
	result_ := Exports.GetRepositoryBranchResource(request)
	result = &result_
	return
}

//go:wasmexport github:server/resources@0.1.0#get-repository-commit-resource
//export github:server/resources@0.1.0#get-repository-commit-resource
func wasmexport_GetRepositoryCommitResource(request0 *uint8, request1 uint32) (result *ToolResult) {
	request := lift_ResourceRequest((*uint8)(request0), (uint32)(request1))
	result_ := Exports.GetRepositoryCommitResource(request)
	result = &result_
	return
}

//go:wasmexport github:server/resources@0.1.0#get-repository-tag-resource
//export github:server/resources@0.1.0#get-repository-tag-resource
func wasmexport_GetRepositoryTagResource(request0 *uint8, request1 uint32) (result *ToolResult) {
	request := lift_ResourceRequest((*uint8)(request0), (uint32)(request1))
	result_ := Exports.GetRepositoryTagResource(request)
	result = &result_
	return
}

//go:wasmexport github:server/resources@0.1.0#get-repository-pr-resource
//export github:server/resources@0.1.0#get-repository-pr-resource
func wasmexport_GetRepositoryPrResource(request0 *uint8, request1 uint32) (result *ToolResult) {
	request := lift_ResourceRequest((*uint8)(request0), (uint32)(request1))
	result_ := Exports.GetRepositoryPrResource(request)
	result = &result_
	return
}
