// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package resources represents the exported interface "github:server/resources@0.1.0".
//
// Resources interface (for MCP resources)
package resources

import (
	"github.com/github/github-mcp-server/internal/github/server/types"
)

// ToolResult represents the type alias "github:server/resources@0.1.0#tool-result".
//
// See [types.ToolResult] for more information.
type ToolResult = types.ToolResult

// ResourceRequest represents the type alias "github:server/resources@0.1.0#resource-request".
//
// See [types.ResourceRequest] for more information.
type ResourceRequest = types.ResourceRequest
