// Code generated by wit-bindgen-go. DO NOT EDIT.

package resources

// Exports represents the caller-defined exports from "github:server/resources@0.1.0".
var Exports struct {
	// GetRepositoryResource represents the caller-defined, exported function "get-repository-resource".
	//
	//	get-repository-resource: func(request: resource-request) -> tool-result
	GetRepositoryResource func(request ResourceRequest) (result ToolResult)

	// GetRepositoryBranchResource represents the caller-defined, exported function "get-repository-branch-resource".
	//
	//	get-repository-branch-resource: func(request: resource-request) -> tool-result
	GetRepositoryBranchResource func(request ResourceRequest) (result ToolResult)

	// GetRepositoryCommitResource represents the caller-defined, exported function "get-repository-commit-resource".
	//
	//	get-repository-commit-resource: func(request: resource-request) -> tool-result
	GetRepositoryCommitResource func(request ResourceRequest) (result ToolResult)

	// GetRepositoryTagResource represents the caller-defined, exported function "get-repository-tag-resource".
	//
	//	get-repository-tag-resource: func(request: resource-request) -> tool-result
	GetRepositoryTagResource func(request ResourceRequest) (result ToolResult)

	// GetRepositoryPrResource represents the caller-defined, exported function "get-repository-pr-resource".
	//
	//	get-repository-pr-resource: func(request: resource-request) -> tool-result
	GetRepositoryPrResource func(request ResourceRequest) (result ToolResult)
}
