// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package githubserver represents the world "github:server/github-server@0.1.0".
//
// Main world that the component implements
package githubserver
