// Code generated by wit-bindgen-go. DO NOT EDIT.

package notifications

// Exports represents the caller-defined exports from "github:server/notifications@0.1.0".
var Exports struct {
	// ListNotifications represents the caller-defined, exported function "list-notifications".
	//
	//	list-notifications: func(request: tool-request) -> tool-result
	ListNotifications func(request ToolRequest) (result ToolResult)

	// GetNotificationDetails represents the caller-defined, exported function "get-notification-details".
	//
	//	get-notification-details: func(request: tool-request) -> tool-result
	GetNotificationDetails func(request ToolRequest) (result ToolResult)

	// DismissNotification represents the caller-defined, exported function "dismiss-notification".
	//
	//	dismiss-notification: func(request: tool-request) -> tool-result
	DismissNotification func(request ToolRequest) (result ToolResult)

	// MarkAllNotificationsRead represents the caller-defined, exported function "mark-all-notifications-read".
	//
	//	mark-all-notifications-read: func(request: tool-request) -> tool-result
	MarkAllNotificationsRead func(request ToolRequest) (result ToolResult)

	// ManageNotificationSubscription represents the caller-defined, exported function "manage-notification-subscription".
	//
	//	manage-notification-subscription: func(request: tool-request) -> tool-result
	ManageNotificationSubscription func(request ToolRequest) (result ToolResult)

	// ManageRepositoryNotificationSubscription represents the caller-defined, exported function "manage-repository-notification-subscription".
	//
	//	manage-repository-notification-subscription: func(request: tool-request) -> tool-result
	ManageRepositoryNotificationSubscription func(request ToolRequest) (result ToolResult)
}
