// Code generated by wit-bindgen-go. DO NOT EDIT.

package notifications

// This file contains wasmimport and wasmexport declarations for "github:server@0.1.0".

//go:wasmexport github:server/notifications@0.1.0#list-notifications
//export github:server/notifications@0.1.0#list-notifications
func wasmexport_ListNotifications(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.ListNotifications(request)
	result = &result_
	return
}

//go:wasmexport github:server/notifications@0.1.0#get-notification-details
//export github:server/notifications@0.1.0#get-notification-details
func wasmexport_GetNotificationDetails(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.GetNotificationDetails(request)
	result = &result_
	return
}

//go:wasmexport github:server/notifications@0.1.0#dismiss-notification
//export github:server/notifications@0.1.0#dismiss-notification
func wasmexport_DismissNotification(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.DismissNotification(request)
	result = &result_
	return
}

//go:wasmexport github:server/notifications@0.1.0#mark-all-notifications-read
//export github:server/notifications@0.1.0#mark-all-notifications-read
func wasmexport_MarkAllNotificationsRead(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.MarkAllNotificationsRead(request)
	result = &result_
	return
}

//go:wasmexport github:server/notifications@0.1.0#manage-notification-subscription
//export github:server/notifications@0.1.0#manage-notification-subscription
func wasmexport_ManageNotificationSubscription(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.ManageNotificationSubscription(request)
	result = &result_
	return
}

//go:wasmexport github:server/notifications@0.1.0#manage-repository-notification-subscription
//export github:server/notifications@0.1.0#manage-repository-notification-subscription
func wasmexport_ManageRepositoryNotificationSubscription(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.ManageRepositoryNotificationSubscription(request)
	result = &result_
	return
}
