// Code generated by wit-bindgen-go. DO NOT EDIT.

package discussions

// Exports represents the caller-defined exports from "github:server/discussions@0.1.0".
var Exports struct {
	// ListDiscussions represents the caller-defined, exported function "list-discussions".
	//
	//	list-discussions: func(request: tool-request) -> tool-result
	ListDiscussions func(request ToolRequest) (result ToolResult)

	// GetDiscussion represents the caller-defined, exported function "get-discussion".
	//
	//	get-discussion: func(request: tool-request) -> tool-result
	GetDiscussion func(request ToolRequest) (result ToolResult)

	// GetDiscussionComments represents the caller-defined, exported function "get-discussion-comments".
	//
	//	get-discussion-comments: func(request: tool-request) -> tool-result
	GetDiscussionComments func(request ToolRequest) (result ToolResult)

	// ListDiscussionCategories represents the caller-defined, exported function "list-discussion-categories".
	//
	//	list-discussion-categories: func(request: tool-request) -> tool-result
	ListDiscussionCategories func(request ToolRequest) (result ToolResult)
}
