// Code generated by wit-bindgen-go. DO NOT EDIT.

package discussions

// This file contains wasmimport and wasmexport declarations for "github:server@0.1.0".

//go:wasmexport github:server/discussions@0.1.0#list-discussions
//export github:server/discussions@0.1.0#list-discussions
func wasmexport_ListDiscussions(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.ListDiscussions(request)
	result = &result_
	return
}

//go:wasmexport github:server/discussions@0.1.0#get-discussion
//export github:server/discussions@0.1.0#get-discussion
func wasmexport_GetDiscussion(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.GetDiscussion(request)
	result = &result_
	return
}

//go:wasmexport github:server/discussions@0.1.0#get-discussion-comments
//export github:server/discussions@0.1.0#get-discussion-comments
func wasmexport_GetDiscussionComments(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.GetDiscussionComments(request)
	result = &result_
	return
}

//go:wasmexport github:server/discussions@0.1.0#list-discussion-categories
//export github:server/discussions@0.1.0#list-discussion-categories
func wasmexport_ListDiscussionCategories(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.ListDiscussionCategories(request)
	result = &result_
	return
}
