// Code generated by wit-bindgen-go. DO NOT EDIT.

package gists

// This file contains wasmimport and wasmexport declarations for "github:server@0.1.0".

//go:wasmexport github:server/gists@0.1.0#list-gists
//export github:server/gists@0.1.0#list-gists
func wasmexport_ListGists(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.ListGists(request)
	result = &result_
	return
}

//go:wasmexport github:server/gists@0.1.0#create-gist
//export github:server/gists@0.1.0#create-gist
func wasmexport_CreateGist(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.CreateGist(request)
	result = &result_
	return
}

//go:wasmexport github:server/gists@0.1.0#update-gist
//export github:server/gists@0.1.0#update-gist
func wasmexport_UpdateGist(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.UpdateGist(request)
	result = &result_
	return
}
