// Code generated by wit-bindgen-go. DO NOT EDIT.

package gists

// Exports represents the caller-defined exports from "github:server/gists@0.1.0".
var Exports struct {
	// ListGists represents the caller-defined, exported function "list-gists".
	//
	//	list-gists: func(request: tool-request) -> tool-result
	ListGists func(request ToolRequest) (result ToolResult)

	// CreateGist represents the caller-defined, exported function "create-gist".
	//
	//	create-gist: func(request: tool-request) -> tool-result
	CreateGist func(request ToolRequest) (result ToolResult)

	// UpdateGist represents the caller-defined, exported function "update-gist".
	//
	//	update-gist: func(request: tool-request) -> tool-result
	UpdateGist func(request ToolRequest) (result ToolResult)
}
