// Code generated by wit-bindgen-go. DO NOT EDIT.

package issues

// Exports represents the caller-defined exports from "github:server/issues@0.1.0".
var Exports struct {
	// GetIssue represents the caller-defined, exported function "get-issue".
	//
	// Issues
	//
	//	get-issue: func(request: tool-request) -> tool-result
	GetIssue func(request ToolRequest) (result ToolResult)

	// SearchIssues represents the caller-defined, exported function "search-issues".
	//
	//	search-issues: func(request: tool-request) -> tool-result
	SearchIssues func(request ToolRequest) (result ToolResult)

	// ListIssues represents the caller-defined, exported function "list-issues".
	//
	//	list-issues: func(request: tool-request) -> tool-result
	ListIssues func(request ToolRequest) (result ToolResult)

	// CreateIssue represents the caller-defined, exported function "create-issue".
	//
	//	create-issue: func(request: tool-request) -> tool-result
	CreateIssue func(request ToolRequest) (result ToolResult)

	// UpdateIssue represents the caller-defined, exported function "update-issue".
	//
	//	update-issue: func(request: tool-request) -> tool-result
	UpdateIssue func(request ToolRequest) (result ToolResult)

	// AddIssueComment represents the caller-defined, exported function "add-issue-comment".
	//
	//	add-issue-comment: func(request: tool-request) -> tool-result
	AddIssueComment func(request ToolRequest) (result ToolResult)

	// GetIssueComments represents the caller-defined, exported function "get-issue-comments".
	//
	//	get-issue-comments: func(request: tool-request) -> tool-result
	GetIssueComments func(request ToolRequest) (result ToolResult)

	// ListIssueTypes represents the caller-defined, exported function "list-issue-types".
	//
	//	list-issue-types: func(request: tool-request) -> tool-result
	ListIssueTypes func(request ToolRequest) (result ToolResult)

	// ListSubIssues represents the caller-defined, exported function "list-sub-issues".
	//
	//	list-sub-issues: func(request: tool-request) -> tool-result
	ListSubIssues func(request ToolRequest) (result ToolResult)

	// AddSubIssue represents the caller-defined, exported function "add-sub-issue".
	//
	//	add-sub-issue: func(request: tool-request) -> tool-result
	AddSubIssue func(request ToolRequest) (result ToolResult)

	// RemoveSubIssue represents the caller-defined, exported function "remove-sub-issue".
	//
	//	remove-sub-issue: func(request: tool-request) -> tool-result
	RemoveSubIssue func(request ToolRequest) (result ToolResult)

	// ReprioritizeSubIssue represents the caller-defined, exported function "reprioritize-sub-issue".
	//
	//	reprioritize-sub-issue: func(request: tool-request) -> tool-result
	ReprioritizeSubIssue func(request ToolRequest) (result ToolResult)

	// AssignCopilotToIssue represents the caller-defined, exported function "assign-copilot-to-issue".
	//
	//	assign-copilot-to-issue: func(request: tool-request) -> tool-result
	AssignCopilotToIssue func(request ToolRequest) (result ToolResult)

	// GetPullRequest represents the caller-defined, exported function "get-pull-request".
	//
	// Pull Requests
	//
	//	get-pull-request: func(request: tool-request) -> tool-result
	GetPullRequest func(request ToolRequest) (result ToolResult)

	// ListPullRequests represents the caller-defined, exported function "list-pull-requests".
	//
	//	list-pull-requests: func(request: tool-request) -> tool-result
	ListPullRequests func(request ToolRequest) (result ToolResult)

	// CreatePullRequest represents the caller-defined, exported function "create-pull-request".
	//
	//	create-pull-request: func(request: tool-request) -> tool-result
	CreatePullRequest func(request ToolRequest) (result ToolResult)

	// UpdatePullRequest represents the caller-defined, exported function "update-pull-request".
	//
	//	update-pull-request: func(request: tool-request) -> tool-result
	UpdatePullRequest func(request ToolRequest) (result ToolResult)

	// MergePullRequest represents the caller-defined, exported function "merge-pull-request".
	//
	//	merge-pull-request: func(request: tool-request) -> tool-result
	MergePullRequest func(request ToolRequest) (result ToolResult)

	// GetPullRequestFiles represents the caller-defined, exported function "get-pull-request-files".
	//
	//	get-pull-request-files: func(request: tool-request) -> tool-result
	GetPullRequestFiles func(request ToolRequest) (result ToolResult)

	// SearchPullRequests represents the caller-defined, exported function "search-pull-requests".
	//
	//	search-pull-requests: func(request: tool-request) -> tool-result
	SearchPullRequests func(request ToolRequest) (result ToolResult)

	// GetPullRequestStatus represents the caller-defined, exported function "get-pull-request-status".
	//
	//	get-pull-request-status: func(request: tool-request) -> tool-result
	GetPullRequestStatus func(request ToolRequest) (result ToolResult)

	// GetPullRequestReviews represents the caller-defined, exported function "get-pull-request-reviews".
	//
	//	get-pull-request-reviews: func(request: tool-request) -> tool-result
	GetPullRequestReviews func(request ToolRequest) (result ToolResult)

	// GetPullRequestReviewComments represents the caller-defined, exported function "get-pull-request-review-comments".
	//
	//	get-pull-request-review-comments: func(request: tool-request) -> tool-result
	GetPullRequestReviewComments func(request ToolRequest) (result ToolResult)

	// GetPullRequestDiff represents the caller-defined, exported function "get-pull-request-diff".
	//
	//	get-pull-request-diff: func(request: tool-request) -> tool-result
	GetPullRequestDiff func(request ToolRequest) (result ToolResult)

	// UpdatePullRequestBranch represents the caller-defined, exported function "update-pull-request-branch".
	//
	//	update-pull-request-branch: func(request: tool-request) -> tool-result
	UpdatePullRequestBranch func(request ToolRequest) (result ToolResult)

	// RequestCopilotReview represents the caller-defined, exported function "request-copilot-review".
	//
	//	request-copilot-review: func(request: tool-request) -> tool-result
	RequestCopilotReview func(request ToolRequest) (result ToolResult)

	// CreateAndSubmitPullRequestReview represents the caller-defined, exported function "create-and-submit-pull-request-review".
	//
	// Reviews
	//
	//	create-and-submit-pull-request-review: func(request: tool-request) -> tool-result
	CreateAndSubmitPullRequestReview func(request ToolRequest) (result ToolResult)

	// CreatePendingPullRequestReview represents the caller-defined, exported function "create-pending-pull-request-review".
	//
	//	create-pending-pull-request-review: func(request: tool-request) -> tool-result
	CreatePendingPullRequestReview func(request ToolRequest) (result ToolResult)

	// AddCommentToPendingReview represents the caller-defined, exported function "add-comment-to-pending-review".
	//
	//	add-comment-to-pending-review: func(request: tool-request) -> tool-result
	AddCommentToPendingReview func(request ToolRequest) (result ToolResult)

	// SubmitPendingPullRequestReview represents the caller-defined, exported function "submit-pending-pull-request-review".
	//
	//	submit-pending-pull-request-review: func(request: tool-request) -> tool-result
	SubmitPendingPullRequestReview func(request ToolRequest) (result ToolResult)

	// DeletePendingPullRequestReview represents the caller-defined, exported function "delete-pending-pull-request-review".
	//
	//	delete-pending-pull-request-review: func(request: tool-request) -> tool-result
	DeletePendingPullRequestReview func(request ToolRequest) (result ToolResult)
}
