// Code generated by wit-bindgen-go. DO NOT EDIT.

package issues

// This file contains wasmimport and wasmexport declarations for "github:server@0.1.0".

//go:wasmexport github:server/issues@0.1.0#get-issue
//export github:server/issues@0.1.0#get-issue
func wasmexport_GetIssue(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.GetIssue(request)
	result = &result_
	return
}

//go:wasmexport github:server/issues@0.1.0#search-issues
//export github:server/issues@0.1.0#search-issues
func wasmexport_SearchIssues(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.SearchIssues(request)
	result = &result_
	return
}

//go:wasmexport github:server/issues@0.1.0#list-issues
//export github:server/issues@0.1.0#list-issues
func wasmexport_ListIssues(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.ListIssues(request)
	result = &result_
	return
}

//go:wasmexport github:server/issues@0.1.0#create-issue
//export github:server/issues@0.1.0#create-issue
func wasmexport_CreateIssue(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.CreateIssue(request)
	result = &result_
	return
}

//go:wasmexport github:server/issues@0.1.0#update-issue
//export github:server/issues@0.1.0#update-issue
func wasmexport_UpdateIssue(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.UpdateIssue(request)
	result = &result_
	return
}

//go:wasmexport github:server/issues@0.1.0#add-issue-comment
//export github:server/issues@0.1.0#add-issue-comment
func wasmexport_AddIssueComment(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.AddIssueComment(request)
	result = &result_
	return
}

//go:wasmexport github:server/issues@0.1.0#get-issue-comments
//export github:server/issues@0.1.0#get-issue-comments
func wasmexport_GetIssueComments(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.GetIssueComments(request)
	result = &result_
	return
}

//go:wasmexport github:server/issues@0.1.0#list-issue-types
//export github:server/issues@0.1.0#list-issue-types
func wasmexport_ListIssueTypes(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.ListIssueTypes(request)
	result = &result_
	return
}

//go:wasmexport github:server/issues@0.1.0#list-sub-issues
//export github:server/issues@0.1.0#list-sub-issues
func wasmexport_ListSubIssues(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.ListSubIssues(request)
	result = &result_
	return
}

//go:wasmexport github:server/issues@0.1.0#add-sub-issue
//export github:server/issues@0.1.0#add-sub-issue
func wasmexport_AddSubIssue(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.AddSubIssue(request)
	result = &result_
	return
}

//go:wasmexport github:server/issues@0.1.0#remove-sub-issue
//export github:server/issues@0.1.0#remove-sub-issue
func wasmexport_RemoveSubIssue(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.RemoveSubIssue(request)
	result = &result_
	return
}

//go:wasmexport github:server/issues@0.1.0#reprioritize-sub-issue
//export github:server/issues@0.1.0#reprioritize-sub-issue
func wasmexport_ReprioritizeSubIssue(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.ReprioritizeSubIssue(request)
	result = &result_
	return
}

//go:wasmexport github:server/issues@0.1.0#assign-copilot-to-issue
//export github:server/issues@0.1.0#assign-copilot-to-issue
func wasmexport_AssignCopilotToIssue(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.AssignCopilotToIssue(request)
	result = &result_
	return
}

//go:wasmexport github:server/issues@0.1.0#get-pull-request
//export github:server/issues@0.1.0#get-pull-request
func wasmexport_GetPullRequest(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.GetPullRequest(request)
	result = &result_
	return
}

//go:wasmexport github:server/issues@0.1.0#list-pull-requests
//export github:server/issues@0.1.0#list-pull-requests
func wasmexport_ListPullRequests(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.ListPullRequests(request)
	result = &result_
	return
}

//go:wasmexport github:server/issues@0.1.0#create-pull-request
//export github:server/issues@0.1.0#create-pull-request
func wasmexport_CreatePullRequest(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.CreatePullRequest(request)
	result = &result_
	return
}

//go:wasmexport github:server/issues@0.1.0#update-pull-request
//export github:server/issues@0.1.0#update-pull-request
func wasmexport_UpdatePullRequest(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.UpdatePullRequest(request)
	result = &result_
	return
}

//go:wasmexport github:server/issues@0.1.0#merge-pull-request
//export github:server/issues@0.1.0#merge-pull-request
func wasmexport_MergePullRequest(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.MergePullRequest(request)
	result = &result_
	return
}

//go:wasmexport github:server/issues@0.1.0#get-pull-request-files
//export github:server/issues@0.1.0#get-pull-request-files
func wasmexport_GetPullRequestFiles(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.GetPullRequestFiles(request)
	result = &result_
	return
}

//go:wasmexport github:server/issues@0.1.0#search-pull-requests
//export github:server/issues@0.1.0#search-pull-requests
func wasmexport_SearchPullRequests(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.SearchPullRequests(request)
	result = &result_
	return
}

//go:wasmexport github:server/issues@0.1.0#get-pull-request-status
//export github:server/issues@0.1.0#get-pull-request-status
func wasmexport_GetPullRequestStatus(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.GetPullRequestStatus(request)
	result = &result_
	return
}

//go:wasmexport github:server/issues@0.1.0#get-pull-request-reviews
//export github:server/issues@0.1.0#get-pull-request-reviews
func wasmexport_GetPullRequestReviews(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.GetPullRequestReviews(request)
	result = &result_
	return
}

//go:wasmexport github:server/issues@0.1.0#get-pull-request-review-comments
//export github:server/issues@0.1.0#get-pull-request-review-comments
func wasmexport_GetPullRequestReviewComments(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.GetPullRequestReviewComments(request)
	result = &result_
	return
}

//go:wasmexport github:server/issues@0.1.0#get-pull-request-diff
//export github:server/issues@0.1.0#get-pull-request-diff
func wasmexport_GetPullRequestDiff(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.GetPullRequestDiff(request)
	result = &result_
	return
}

//go:wasmexport github:server/issues@0.1.0#update-pull-request-branch
//export github:server/issues@0.1.0#update-pull-request-branch
func wasmexport_UpdatePullRequestBranch(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.UpdatePullRequestBranch(request)
	result = &result_
	return
}

//go:wasmexport github:server/issues@0.1.0#request-copilot-review
//export github:server/issues@0.1.0#request-copilot-review
func wasmexport_RequestCopilotReview(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.RequestCopilotReview(request)
	result = &result_
	return
}

//go:wasmexport github:server/issues@0.1.0#create-and-submit-pull-request-review
//export github:server/issues@0.1.0#create-and-submit-pull-request-review
func wasmexport_CreateAndSubmitPullRequestReview(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.CreateAndSubmitPullRequestReview(request)
	result = &result_
	return
}

//go:wasmexport github:server/issues@0.1.0#create-pending-pull-request-review
//export github:server/issues@0.1.0#create-pending-pull-request-review
func wasmexport_CreatePendingPullRequestReview(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.CreatePendingPullRequestReview(request)
	result = &result_
	return
}

//go:wasmexport github:server/issues@0.1.0#add-comment-to-pending-review
//export github:server/issues@0.1.0#add-comment-to-pending-review
func wasmexport_AddCommentToPendingReview(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.AddCommentToPendingReview(request)
	result = &result_
	return
}

//go:wasmexport github:server/issues@0.1.0#submit-pending-pull-request-review
//export github:server/issues@0.1.0#submit-pending-pull-request-review
func wasmexport_SubmitPendingPullRequestReview(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.SubmitPendingPullRequestReview(request)
	result = &result_
	return
}

//go:wasmexport github:server/issues@0.1.0#delete-pending-pull-request-review
//export github:server/issues@0.1.0#delete-pending-pull-request-review
func wasmexport_DeletePendingPullRequestReview(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.DeletePendingPullRequestReview(request)
	result = &result_
	return
}
