// Code generated by wit-bindgen-go. DO NOT EDIT.

package users

// This file contains wasmimport and wasmexport declarations for "github:server@0.1.0".

//go:wasmexport github:server/users@0.1.0#search-users
//export github:server/users@0.1.0#search-users
func wasmexport_SearchUsers(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.SearchUsers(request)
	result = &result_
	return
}

//go:wasmexport github:server/users@0.1.0#search-orgs
//export github:server/users@0.1.0#search-orgs
func wasmexport_SearchOrgs(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.SearchOrgs(request)
	result = &result_
	return
}

//go:wasmexport github:server/users@0.1.0#get-me
//export github:server/users@0.1.0#get-me
func wasmexport_GetMe(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.GetMe(request)
	result = &result_
	return
}

//go:wasmexport github:server/users@0.1.0#get-teams
//export github:server/users@0.1.0#get-teams
func wasmexport_GetTeams(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.GetTeams(request)
	result = &result_
	return
}

//go:wasmexport github:server/users@0.1.0#get-team-members
//export github:server/users@0.1.0#get-team-members
func wasmexport_GetTeamMembers(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.GetTeamMembers(request)
	result = &result_
	return
}
