// Code generated by wit-bindgen-go. DO NOT EDIT.

package users

// Exports represents the caller-defined exports from "github:server/users@0.1.0".
var Exports struct {
	// SearchUsers represents the caller-defined, exported function "search-users".
	//
	//	search-users: func(request: tool-request) -> tool-result
	SearchUsers func(request ToolRequest) (result ToolResult)

	// SearchOrgs represents the caller-defined, exported function "search-orgs".
	//
	//	search-orgs: func(request: tool-request) -> tool-result
	SearchOrgs func(request ToolRequest) (result ToolResult)

	// GetMe represents the caller-defined, exported function "get-me".
	//
	//	get-me: func(request: tool-request) -> tool-result
	GetMe func(request ToolRequest) (result ToolResult)

	// GetTeams represents the caller-defined, exported function "get-teams".
	//
	//	get-teams: func(request: tool-request) -> tool-result
	GetTeams func(request ToolRequest) (result ToolResult)

	// GetTeamMembers represents the caller-defined, exported function "get-team-members".
	//
	//	get-team-members: func(request: tool-request) -> tool-result
	GetTeamMembers func(request ToolRequest) (result ToolResult)
}
