// Code generated by wit-bindgen-go. DO NOT EDIT.

package actions

import (
	"github.com/github/github-mcp-server/internal/github/server/types"
	"go.bytecodealliance.org/cm"
)

func lift_ToolRequest(f0 *uint8, f1 uint32, f2 *uint8, f3 uint32) (v types.ToolRequest) {
	v.Name = cm.LiftString[string](f0, f1)
	v.Params = cm.LiftString[string](f2, f3)
	return
}
