// Code generated by wit-bindgen-go. DO NOT EDIT.

package actions

// This file contains wasmimport and wasmexport declarations for "github:server@0.1.0".

//go:wasmexport github:server/actions@0.1.0#list-workflows
//export github:server/actions@0.1.0#list-workflows
func wasmexport_ListWorkflows(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.ListWorkflows(request)
	result = &result_
	return
}

//go:wasmexport github:server/actions@0.1.0#list-workflow-runs
//export github:server/actions@0.1.0#list-workflow-runs
func wasmexport_ListWorkflowRuns(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.ListWorkflowRuns(request)
	result = &result_
	return
}

//go:wasmexport github:server/actions@0.1.0#get-workflow-run
//export github:server/actions@0.1.0#get-workflow-run
func wasmexport_GetWorkflowRun(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.GetWorkflowRun(request)
	result = &result_
	return
}

//go:wasmexport github:server/actions@0.1.0#get-workflow-run-logs
//export github:server/actions@0.1.0#get-workflow-run-logs
func wasmexport_GetWorkflowRunLogs(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.GetWorkflowRunLogs(request)
	result = &result_
	return
}

//go:wasmexport github:server/actions@0.1.0#list-workflow-jobs
//export github:server/actions@0.1.0#list-workflow-jobs
func wasmexport_ListWorkflowJobs(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.ListWorkflowJobs(request)
	result = &result_
	return
}

//go:wasmexport github:server/actions@0.1.0#get-job-logs
//export github:server/actions@0.1.0#get-job-logs
func wasmexport_GetJobLogs(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.GetJobLogs(request)
	result = &result_
	return
}

//go:wasmexport github:server/actions@0.1.0#list-workflow-run-artifacts
//export github:server/actions@0.1.0#list-workflow-run-artifacts
func wasmexport_ListWorkflowRunArtifacts(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.ListWorkflowRunArtifacts(request)
	result = &result_
	return
}

//go:wasmexport github:server/actions@0.1.0#download-workflow-run-artifact
//export github:server/actions@0.1.0#download-workflow-run-artifact
func wasmexport_DownloadWorkflowRunArtifact(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.DownloadWorkflowRunArtifact(request)
	result = &result_
	return
}

//go:wasmexport github:server/actions@0.1.0#get-workflow-run-usage
//export github:server/actions@0.1.0#get-workflow-run-usage
func wasmexport_GetWorkflowRunUsage(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.GetWorkflowRunUsage(request)
	result = &result_
	return
}

//go:wasmexport github:server/actions@0.1.0#run-workflow
//export github:server/actions@0.1.0#run-workflow
func wasmexport_RunWorkflow(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.RunWorkflow(request)
	result = &result_
	return
}

//go:wasmexport github:server/actions@0.1.0#rerun-workflow-run
//export github:server/actions@0.1.0#rerun-workflow-run
func wasmexport_RerunWorkflowRun(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.RerunWorkflowRun(request)
	result = &result_
	return
}

//go:wasmexport github:server/actions@0.1.0#rerun-failed-jobs
//export github:server/actions@0.1.0#rerun-failed-jobs
func wasmexport_RerunFailedJobs(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.RerunFailedJobs(request)
	result = &result_
	return
}

//go:wasmexport github:server/actions@0.1.0#cancel-workflow-run
//export github:server/actions@0.1.0#cancel-workflow-run
func wasmexport_CancelWorkflowRun(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.CancelWorkflowRun(request)
	result = &result_
	return
}

//go:wasmexport github:server/actions@0.1.0#delete-workflow-run-logs
//export github:server/actions@0.1.0#delete-workflow-run-logs
func wasmexport_DeleteWorkflowRunLogs(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.DeleteWorkflowRunLogs(request)
	result = &result_
	return
}
