// Code generated by wit-bindgen-go. DO NOT EDIT.

package actions

// Exports represents the caller-defined exports from "github:server/actions@0.1.0".
var Exports struct {
	// ListWorkflows represents the caller-defined, exported function "list-workflows".
	//
	//	list-workflows: func(request: tool-request) -> tool-result
	ListWorkflows func(request ToolRequest) (result ToolResult)

	// ListWorkflowRuns represents the caller-defined, exported function "list-workflow-runs".
	//
	//	list-workflow-runs: func(request: tool-request) -> tool-result
	ListWorkflowRuns func(request ToolRequest) (result ToolResult)

	// GetWorkflowRun represents the caller-defined, exported function "get-workflow-run".
	//
	//	get-workflow-run: func(request: tool-request) -> tool-result
	GetWorkflowRun func(request ToolRequest) (result ToolResult)

	// GetWorkflowRunLogs represents the caller-defined, exported function "get-workflow-run-logs".
	//
	//	get-workflow-run-logs: func(request: tool-request) -> tool-result
	GetWorkflowRunLogs func(request ToolRequest) (result ToolResult)

	// ListWorkflowJobs represents the caller-defined, exported function "list-workflow-jobs".
	//
	//	list-workflow-jobs: func(request: tool-request) -> tool-result
	ListWorkflowJobs func(request ToolRequest) (result ToolResult)

	// GetJobLogs represents the caller-defined, exported function "get-job-logs".
	//
	//	get-job-logs: func(request: tool-request) -> tool-result
	GetJobLogs func(request ToolRequest) (result ToolResult)

	// ListWorkflowRunArtifacts represents the caller-defined, exported function "list-workflow-run-artifacts".
	//
	//	list-workflow-run-artifacts: func(request: tool-request) -> tool-result
	ListWorkflowRunArtifacts func(request ToolRequest) (result ToolResult)

	// DownloadWorkflowRunArtifact represents the caller-defined, exported function "download-workflow-run-artifact".
	//
	//	download-workflow-run-artifact: func(request: tool-request) -> tool-result
	DownloadWorkflowRunArtifact func(request ToolRequest) (result ToolResult)

	// GetWorkflowRunUsage represents the caller-defined, exported function "get-workflow-run-usage".
	//
	//	get-workflow-run-usage: func(request: tool-request) -> tool-result
	GetWorkflowRunUsage func(request ToolRequest) (result ToolResult)

	// RunWorkflow represents the caller-defined, exported function "run-workflow".
	//
	//	run-workflow: func(request: tool-request) -> tool-result
	RunWorkflow func(request ToolRequest) (result ToolResult)

	// RerunWorkflowRun represents the caller-defined, exported function "rerun-workflow-run".
	//
	//	rerun-workflow-run: func(request: tool-request) -> tool-result
	RerunWorkflowRun func(request ToolRequest) (result ToolResult)

	// RerunFailedJobs represents the caller-defined, exported function "rerun-failed-jobs".
	//
	//	rerun-failed-jobs: func(request: tool-request) -> tool-result
	RerunFailedJobs func(request ToolRequest) (result ToolResult)

	// CancelWorkflowRun represents the caller-defined, exported function "cancel-workflow-run".
	//
	//	cancel-workflow-run: func(request: tool-request) -> tool-result
	CancelWorkflowRun func(request ToolRequest) (result ToolResult)

	// DeleteWorkflowRunLogs represents the caller-defined, exported function "delete-workflow-run-logs".
	//
	//	delete-workflow-run-logs: func(request: tool-request) -> tool-result
	DeleteWorkflowRunLogs func(request ToolRequest) (result ToolResult)
}
