// Code generated by wit-bindgen-go. DO NOT EDIT.

package dynamic

// Exports represents the caller-defined exports from "github:server/dynamic@0.1.0".
var Exports struct {
	// ListAvailableToolsets represents the caller-defined, exported function "list-available-toolsets".
	//
	//	list-available-toolsets: func(request: tool-request) -> tool-result
	ListAvailableToolsets func(request ToolRequest) (result ToolResult)

	// GetToolsetsTools represents the caller-defined, exported function "get-toolsets-tools".
	//
	//	get-toolsets-tools: func(request: tool-request) -> tool-result
	GetToolsetsTools func(request ToolRequest) (result ToolResult)

	// EnableToolset represents the caller-defined, exported function "enable-toolset".
	//
	//	enable-toolset: func(request: tool-request) -> tool-result
	EnableToolset func(request ToolRequest) (result ToolResult)
}
