// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package dynamic represents the exported interface "github:server/dynamic@0.1.0".
//
// Dynamic toolsets
package dynamic

import (
	"github.com/github/github-mcp-server/internal/github/server/types"
)

// ToolResult represents the type alias "github:server/dynamic@0.1.0#tool-result".
//
// See [types.ToolResult] for more information.
type ToolResult = types.ToolResult

// ToolRequest represents the type alias "github:server/dynamic@0.1.0#tool-request".
//
// See [types.ToolRequest] for more information.
type ToolRequest = types.ToolRequest
