// Code generated by wit-bindgen-go. DO NOT EDIT.

package dynamic

// This file contains wasmimport and wasmexport declarations for "github:server@0.1.0".

//go:wasmexport github:server/dynamic@0.1.0#list-available-toolsets
//export github:server/dynamic@0.1.0#list-available-toolsets
func wasmexport_ListAvailableToolsets(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.ListAvailableToolsets(request)
	result = &result_
	return
}

//go:wasmexport github:server/dynamic@0.1.0#get-toolsets-tools
//export github:server/dynamic@0.1.0#get-toolsets-tools
func wasmexport_GetToolsetsTools(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.GetToolsetsTools(request)
	result = &result_
	return
}

//go:wasmexport github:server/dynamic@0.1.0#enable-toolset
//export github:server/dynamic@0.1.0#enable-toolset
func wasmexport_EnableToolset(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_ToolRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.EnableToolset(request)
	result = &result_
	return
}
