// Code generated by wit-bindgen-go. DO NOT EDIT.

package prompts

// This file contains wasmimport and wasmexport declarations for "github:server@0.1.0".

//go:wasmexport github:server/prompts@0.1.0#assign-coding-agent-prompt
//export github:server/prompts@0.1.0#assign-coding-agent-prompt
func wasmexport_AssignCodingAgentPrompt(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_PromptRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.AssignCodingAgentPrompt(request)
	result = &result_
	return
}

//go:wasmexport github:server/prompts@0.1.0#issue-to-fix-workflow-prompt
//export github:server/prompts@0.1.0#issue-to-fix-workflow-prompt
func wasmexport_IssueToFixWorkflowPrompt(request0 *uint8, request1 uint32, request2 *uint8, request3 uint32) (result *ToolResult) {
	request := lift_PromptRequest((*uint8)(request0), (uint32)(request1), (*uint8)(request2), (uint32)(request3))
	result_ := Exports.IssueToFixWorkflowPrompt(request)
	result = &result_
	return
}
