// Code generated by wit-bindgen-go. DO NOT EDIT.

package prompts

// Exports represents the caller-defined exports from "github:server/prompts@0.1.0".
var Exports struct {
	// AssignCodingAgentPrompt represents the caller-defined, exported function "assign-coding-agent-prompt".
	//
	//	assign-coding-agent-prompt: func(request: prompt-request) -> tool-result
	AssignCodingAgentPrompt func(request PromptRequest) (result ToolResult)

	// IssueToFixWorkflowPrompt represents the caller-defined, exported function "issue-to-fix-workflow-prompt".
	//
	//	issue-to-fix-workflow-prompt: func(request: prompt-request) -> tool-result
	IssueToFixWorkflowPrompt func(request PromptRequest) (result ToolResult)
}
