// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package prompts represents the exported interface "github:server/prompts@0.1.0".
//
// Prompts interface (for workflow generation)
package prompts

import (
	"github.com/github/github-mcp-server/internal/github/server/types"
)

// ToolResult represents the type alias "github:server/prompts@0.1.0#tool-result".
//
// See [types.ToolResult] for more information.
type ToolResult = types.ToolResult

// PromptRequest represents the type alias "github:server/prompts@0.1.0#prompt-request".
//
// See [types.PromptRequest] for more information.
type PromptRequest = types.PromptRequest
