// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package monotonicclock represents the imported interface "wasi:clocks/monotonic-clock@0.2.0".
package monotonicclock

// Instant represents the u64 "wasi:clocks/monotonic-clock@0.2.0#instant".
//
//	type instant = u64
type Instant uint64

// Now represents the imported function "now".
//
//	now: func() -> instant
//
//go:nosplit
func Now() (result Instant) {
	result0 := wasmimport_Now()
	result = (Instant)((uint64)(result0))
	return
}
