// Code generated by wit-bindgen-go. DO NOT EDIT.

package monotonicclock

// This file contains wasmimport and wasmexport declarations for "wasi:clocks@0.2.0".

//go:wasmimport wasi:clocks/monotonic-clock@0.2.0 now
//go:noescape
func wasmimport_Now() (result0 uint64)
